# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Petar Gjorgievski
title: DevOps Engineer | AWS Solutions Architect
email: petar.gjorgievski@tuliptp.com
website: tuliptp.com

# Social links
twitter_username: PetarGjorgievs2
github_username:  PetarGjorgievski94
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: micevivica
linkedin_username: petar-gjorgievski-a76b64164/
# pinterest_username: jekyll
#youtube_username: ivica.micev
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Skilled DevOps Engineer with a big passion for the cloud with profficient hands on experience delivering AWS workloads using infrastructure as code and DevOps principles and metodologies.

  I am most skilled in: <mark>AWS</mark>, <mark>Scripting Languges</mark>, <mark>Infrastructure as a code</mark>, <mark>Cloud Solutions</mark>, <mark>Ansible</mark>

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience

# Certifications Section
certification_title: Certifications

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my professional interests some of my other interests and hobbies include:
   - Skiing
   - Playing music
   - Gaming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
